/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.cliente.userprofile;

import dev.cliente.mainframe.MainFrame;
import dev.servidor.dto.MessageDTO;
import dev.servidor.dto.ProfileDTO;
import dev.servidor.model.UserViewModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author raphael.fachim
 */
public class ProfileView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProfileView
     */
    
    MainFrame mainFrame;
    ProfileDTO profile;
    
    List<MessageDTO> messagesDTO = new ArrayList<MessageDTO>();
    
    UserViewModel userViewModel;
    
    public ProfileView(MainFrame mainFrame, UserViewModel userViewModel, ProfileDTO profile) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.userViewModel = userViewModel;
        this.profile = profile;
        
        setUserInfo();
        getMessagesList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUserPhoto = new javax.swing.JPanel();
        panelUserInfo = new javax.swing.JPanel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblCreated = new javax.swing.JLabel();
        txtFieldUser = new javax.swing.JTextField();
        txtFieldDateOfBirth = new javax.swing.JTextField();
        txtFieldCreated = new javax.swing.JTextField();
        panelUserMessages = new javax.swing.JPanel();
        lblActiveMessages = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMessages = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnNewMessage = new javax.swing.JButton();

        panelUserPhoto.setPreferredSize(new java.awt.Dimension(160, 160));

        javax.swing.GroupLayout panelUserPhotoLayout = new javax.swing.GroupLayout(panelUserPhoto);
        panelUserPhoto.setLayout(panelUserPhotoLayout);
        panelUserPhotoLayout.setHorizontalGroup(
            panelUserPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        panelUserPhotoLayout.setVerticalGroup(
            panelUserPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        lblDateOfBirth.setText("Date of Birth:");

        lblUser.setText("User: ");

        lblCreated.setText("Created:");

        javax.swing.GroupLayout panelUserInfoLayout = new javax.swing.GroupLayout(panelUserInfo);
        panelUserInfo.setLayout(panelUserInfoLayout);
        panelUserInfoLayout.setHorizontalGroup(
            panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserInfoLayout.createSequentialGroup()
                .addGroup(panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserInfoLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldUser))
                    .addGroup(panelUserInfoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblDateOfBirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                    .addGroup(panelUserInfoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblCreated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldCreated, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelUserInfoLayout.setVerticalGroup(
            panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtFieldDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreated))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lblActiveMessages.setText("Active messages:");

        tableMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message Title", "Date"
            }
        ));
        jScrollPane1.setViewportView(tableMessages);

        javax.swing.GroupLayout panelUserMessagesLayout = new javax.swing.GroupLayout(panelUserMessages);
        panelUserMessages.setLayout(panelUserMessagesLayout);
        panelUserMessagesLayout.setHorizontalGroup(
            panelUserMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserMessagesLayout.createSequentialGroup()
                        .addComponent(lblActiveMessages)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelUserMessagesLayout.setVerticalGroup(
            panelUserMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserMessagesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblActiveMessages)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnNewMessage.setText("New Message");
        btnNewMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnNewMessage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelUserMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelUserMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnNewMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMessageActionPerformed
        newMessageDemo();
    }//GEN-LAST:event_btnNewMessageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNewMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveMessages;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panelUserInfo;
    private javax.swing.JPanel panelUserMessages;
    private javax.swing.JPanel panelUserPhoto;
    private javax.swing.JTable tableMessages;
    private javax.swing.JTextField txtFieldCreated;
    private javax.swing.JTextField txtFieldDateOfBirth;
    private javax.swing.JTextField txtFieldUser;
    // End of variables declaration//GEN-END:variables

    private void setUserInfo() {
        this.txtFieldUser.setText(profile.getFullName());
        this.txtFieldCreated.setText(profile.getCreated().toString());
        this.txtFieldDateOfBirth.setText(profile.getBithDate().toString());
    }
    
    private void getMessagesList() {
        this.setMessagesDTO(userViewModel.getMessagesByProfile(profile));
        MessageTableModel messageTableModel = new MessageTableModel(this.getMessagesDTO());
        this.tableMessages.setModel(messageTableModel);
        
        configTableHeaders();
    }
    
    private void configTableHeaders(){
        TableColumnModel usersTableHeader = this.tableMessages.getTableHeader().getColumnModel();
        
        usersTableHeader.getColumn(0).setHeaderValue("Message");
        usersTableHeader.getColumn(1).setHeaderValue("Date");
    }

    public List<MessageDTO> getMessagesDTO() {
        return messagesDTO;
    }

    public void setMessagesDTO(List<MessageDTO> messagesDTO) {
        this.messagesDTO = messagesDTO;
    }

    private void newMessageDemo() {
       getUserViewModel().postNewMessage(this.profile, new MessageDTO("J.Al", "Foo message by " + this.profile.getFullName(), new Date()));
    }

    public UserViewModel getUserViewModel() {
        return userViewModel;
    }
    
}
